# Generated by Django 4.0 on 2022-01-03 23:38

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import program.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', localflavor.br.models.BRCPFField(help_text='Formato: 00011122233', max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='CPF ')),
                ('email', models.EmailField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Aceita'), (3, 'Cancelada')], default=1)),
                ('indicated_cpf', localflavor.br.models.BRCPFField(max_length=14, validators=[program.models.validate_cpf_indicated], verbose_name='CPF indicado')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('client_cpf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_cpf', to='program.client', verbose_name='Cliente')),
            ],
        ),
    ]
