# Generated by Django 4.0 on 2022-01-02 23:35

from django.db import migrations, models
import localflavor.br.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', localflavor.br.models.BRCPFField(help_text='Formato: 00011122233', max_length=14, primary_key=True, serialize=False, verbose_name='CPF ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Formato DDD + Número', max_length=128, region='BR', verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255)),
                ('creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do usuário indicador')),
                ('target_cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do usuário indicado')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
