# Generated by Django 4.0 on 2022-01-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
