# Generated by Django 4.0 on 2022-01-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indication',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Aceita'), (3, 'Cancelada')], default=1),
        ),
    ]
