# Generated by Django 4.0 on 2022-01-04 02:58

from django.db import migrations
import localflavor.br.models
import program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_indication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='indicated_cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, validators=[program.models.validate_cpf_indicated, program.models.validate_exists_another_indication], verbose_name='CPF indicado'),
        ),
    ]
